# Generated by Django 3.1.7 on 2021-03-31 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='cname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='pcategory',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='pdesc',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='pimage',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='pname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='pprice',
            new_name='price',
        ),
    ]
